// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/baemestrada-source/bitsports/ent/categories"
	"github.com/baemestrada-source/bitsports/ent/products"
	"github.com/baemestrada-source/bitsports/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	categoriesFields := schema.Categories{}.Fields()
	_ = categoriesFields
	// categoriesDescName is the schema descriptor for name field.
	categoriesDescName := categoriesFields[0].Descriptor()
	// categories.NameValidator is a validator for the "name" field. It is called by the builders before save.
	categories.NameValidator = categoriesDescName.Validators[0].(func(string) error)
	productsFields := schema.Products{}.Fields()
	_ = productsFields
	// productsDescName is the schema descriptor for name field.
	productsDescName := productsFields[0].Descriptor()
	// products.NameValidator is a validator for the "name" field. It is called by the builders before save.
	products.NameValidator = productsDescName.Validators[0].(func(string) error)
}
