// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Categories is the predicate function for categories builders.
type Categories func(*sql.Selector)

// Products is the predicate function for products builders.
type Products func(*sql.Selector)

// Users is the predicate function for users builders.
type Users func(*sql.Selector)
